name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    name: Apply Labels
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply PR labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
